### ISSUE TITLE
Gentoo support

### ISSUE THREAD

**Issue by CyberTailor** [kpcyrd/what-the-src#15]
Two locations need to be scanned:

1. `metadata/md5-cache/${CATEGORY}/${PACKAGE}-${VERSION}` to get `SRC_URI`
2. `${CATEGORY}/${PACKAGE}/Manifest` to get SHA-256 and BLAKE2b hashsums and size ([spec](https://www.gentoo.org/glep/glep-0074.html))

Repository cache can be found in the [official mirror](https://github.com/gentoo-mirror/gentoo).

**Comment by kpcyrd** [comment]
What's the difference between these two?

- `https://github.com/gentoo/gentoo`
- `https://github.com/gentoo-mirror/gentoo`

They both seem to contain all 3 files (Manifest, metadata.xml and the .ebuilds), not sure if I'm missing something.

**Comment by kpcyrd** [comment]
I think I figured it out, this file only exists on `gentoo-mirror/gentoo`:

https://github.com/gentoo-mirror/gentoo/blob/stable/metadata/md5-cache/sys-apps/ripgrep-14.1.0
